env:
    credentials: "ENCRYPTED[!c87471ba6f0de4b674627c84c784fc50e2410af80574741aa68ef1be5f39ea7b6eac084cc05aa4f40668018bb04e1180!]"
    rcloneconfig: "ENCRYPTED[!12e97400727ac92f86b04217832f60a425d94f7a4969af84c7a6ba2999fe6d97abe5cd7184d2c2f6105cc423f1ddc999!]"
    tokentl: "ENCRYPTED[!56a35db7cfc23137ba1fdaf675be519eea25eb49e1f4a5c11539d7f9ac9f8418f2ac81651516beacd3d07a54ab7c7071!]"
    idtl: "ENCRYPTED[!8e4088eb34868a764c92bcdb3e77693e9fab75cdafe062109f03666bf5ce4bfb5d3a9afe4e32d4bac777bbc3a0013dfd!]"
    build: lunch havoc_RMX1941-userdebug;mka bacon

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - git config --global user.name "imnathanzero"
       - git config --global user.email "nathannxx@proton.me"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy nath:havoc/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="sync havoc"
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init --depth=1 -u https://github.com/imnathanzero/android_manifest_havoc.git -b ten
      - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - git clone --depth=1 https://github.com/imnathanzero/android_device_realme_RMX1941 -b havoc-10 device/realme/RMX1941
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="nathan"
      - export BUILD_HOSTNAME="thickdaddy27"
      - export KBUILD_BUILD_USER="nathan"
      - export KBUILD_BUILD_HOST="thickdaddy27"
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build qassa for RMX2185 Started!"
#      - ./collect.sh
      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/RMX2185/ && ls qassa*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz nath:havoc -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"

