env:
    credentials: "ENCRYPTED[!c87471ba6f0de4b674627c84c784fc50e2410af80574741aa68ef1be5f39ea7b6eac084cc05aa4f40668018bb04e1180!]"
    rcloneconfig: "ENCRYPTED[338631f3bb0e72673080c41281aa5390b11b65d4eec34473c22d143d030023079a8d43d314e40939d231ee8a5f4b8844]"
    tokentl: "ENCRYPTED[ba5a2c2c1e892119770f8b26ebe0da64a99cad7ef9a334730ac2c418a38edad8158c52f0ca79b2ee31f8cc222fee5516]"
    idtl: "ENCRYPTED[fc24d869006721c0d8cc0d8eb137e1dc6d7eeae68bffca05e82f9d56f9339e7e1c510cb1e1f5d9571e6813b736b80e62]"
    make: brunch RMX1941

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - git config --global user.name "imnathanzero"
       - git config --global user.email "nathannxx@proton.me"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy nath:havoc/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="sync havoc"
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init --depth=1 -u https://github.com/imnathanzero/android_manifest_havoc -b ten
      - git clone --depth=1 https://github.com/imnathanzero/android_device_realme_RMX1941 -b havoc-10 device/realme/RMX1941
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="nathan"
      - export BUILD_HOSTNAME="thickdaddy27"
      - export KBUILD_BUILD_USER="nathan"
      - export KBUILD_BUILD_HOST="thickdaddy27"
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build qassa for RMX2185 Started!"
#      - ./collect.sh
      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/RMX2185/ && ls qassa*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz nath:havoc -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"

